"""initial schema: users, facts, section_states, banker_edits

Revision ID: 362ba273519d
Revises: 
Create Date: 2026-08-01 07:45:50.907761

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '362ba273519d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banker_edits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('editor', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('after', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_banker_edits_entry_id'), 'banker_edits', ['entry_id'], unique=False)
    op.create_table('facts',
    sa.Column('fact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance_kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provenance_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provenance_snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provenance_supersedes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('supplied_by', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['provenance_supersedes'], ['facts.fact_id'], ),
    sa.PrimaryKeyConstraint('fact_id')
    )
    op.create_index(op.f('ix_facts_confirmed'), 'facts', ['confirmed'], unique=False)
    op.create_index(op.f('ix_facts_key'), 'facts', ['key'], unique=False)
    op.create_index('ix_facts_key_confirmed', 'facts', ['key', 'confirmed'], unique=False)
    op.create_index(op.f('ix_facts_provenance_supersedes'), 'facts', ['provenance_supersedes'], unique=False)
    op.create_table('section_states',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('entry_id')
    )
    op.create_table('users',
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_salt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('section_states')
    op.drop_index(op.f('ix_facts_provenance_supersedes'), table_name='facts')
    op.drop_index('ix_facts_key_confirmed', table_name='facts')
    op.drop_index(op.f('ix_facts_key'), table_name='facts')
    op.drop_index(op.f('ix_facts_confirmed'), table_name='facts')
    op.drop_table('facts')
    op.drop_index(op.f('ix_banker_edits_entry_id'), table_name='banker_edits')
    op.drop_table('banker_edits')
    # ### end Alembic commands ###
